# Global
.level = ALL

# Klassenspezifisches
Pizza.level = FINE
PizzaStart.level = INFO
Customer.level = FINE

# Handler: Konsole + Datei
handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler

# Konsole
java.util.logging.ConsoleHandler.level = WARNING
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Datei
java.util.logging.FileHandler.level = WARNING
java.util.logging.FileHandler.pattern = logs/pizza_log_%u.log
# Max. Größe pro Datei: 500 KB
java.util.logging.FileHandler.limit = 500000
# Max. 3 rotierende Dateien (danach wird überschrieben)
java.util.logging.FileHandler.count = 3
# Logs werden angehängt, nicht überschrieben
java.util.logging.FileHandler.append = true
# Einfaches Format für Datei-Logs
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter